# Netlify configuration for SpeakFlow web app
[build]
  command = "npm install && npx expo export --platform web"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

# SPA redirect for React Navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
